### ISSUE TITLE
use cases should not overlap?

### ISSUE THREAD

**Issue by mabablue** [i-adopt/usecase_analysis#8]
data integration vs data mining

**Comment by gwemon** [comment]
I think that we should avoid overlaps but some use cases will have common requirements.
Regarding the specific issue of data integration vs data mining I still think we should have both and I would place them in different groups: imho data integration is a manipulation of dataset (i.e. G4) while data mining is more about access to data and access to machine readable information (i.e. G3).

**Comment by graybeal** [comment]
To me the difference is that data mining is about looking within data (in one or more data sets) to learn information about the relationships of the data. The output is the information that you've learned, e.g., that people who buy diapers buy beer. (True story!)

Whereas data integration is about merging "more than one data set" into "one data set". The output is explicitly a new data set, containing some or all of the original data.

I don't see any overlap there. (Well, yes, both access data, but and so they may share some requirements. But that's unavoidable and appropriate, because the actual work performed to achieve use cases will have to overlap.)

**Comment by mabablue** [comment]
thanks both for the clarification. But still not sure if JG agrees to put data mining use case in G3? I would agree to do so (and will upload now an updated csv with the IDs suggested by Gwen).

**Comment by graybeal** [comment]
yes that's where it should go in my opinion
